--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: autores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.autores (
    id bigint NOT NULL,
    anio_muerte integer,
    anio_nacimiento integer,
    nombre character varying(1024) NOT NULL
);


ALTER TABLE public.autores OWNER TO postgres;

--
-- Name: autores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.autores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.autores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idiomas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.idiomas (
    id bigint NOT NULL,
    codigo character varying(5) NOT NULL
);


ALTER TABLE public.idiomas OWNER TO postgres;

--
-- Name: idiomas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.idiomas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.idiomas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: libros; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.libros (
    id bigint NOT NULL,
    descargas bigint NOT NULL,
    titulo character varying(1024) NOT NULL
);


ALTER TABLE public.libros OWNER TO postgres;

--
-- Name: libros_autores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.libros_autores (
    libro_id bigint NOT NULL,
    autor_id bigint NOT NULL
);


ALTER TABLE public.libros_autores OWNER TO postgres;

--
-- Name: libros_idiomas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.libros_idiomas (
    libro_id bigint NOT NULL,
    idioma_id bigint NOT NULL
);


ALTER TABLE public.libros_idiomas OWNER TO postgres;

--
-- Name: autores autores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.autores
    ADD CONSTRAINT autores_pkey PRIMARY KEY (id);


--
-- Name: idiomas idiomas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.idiomas
    ADD CONSTRAINT idiomas_pkey PRIMARY KEY (id);


--
-- Name: autores uc_autores_nombre; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.autores
    ADD CONSTRAINT uc_autores_nombre UNIQUE (nombre);


--
-- Name: idiomas uc_idiomas_codigo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.idiomas
    ADD CONSTRAINT uc_idiomas_codigo UNIQUE (codigo);


--
-- Name: libros uc_libros_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.libros
    ADD CONSTRAINT uc_libros_id PRIMARY KEY (id);


--
-- Name: libros_autores fk_libros_autores_autor_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.libros_autores
    ADD CONSTRAINT fk_libros_autores_autor_id FOREIGN KEY (autor_id) REFERENCES public.autores(id);


--
-- Name: libros_autores fk_libros_autores_libro_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.libros_autores
    ADD CONSTRAINT fk_libros_autores_libro_id FOREIGN KEY (libro_id) REFERENCES public.libros(id);


--
-- Name: libros_idiomas fk_libros_idiomas_idioma_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.libros_idiomas
    ADD CONSTRAINT fk_libros_idiomas_idioma_id FOREIGN KEY (idioma_id) REFERENCES public.idiomas(id);


--
-- Name: libros_idiomas fk_libros_idiomas_libro_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.libros_idiomas
    ADD CONSTRAINT fk_libros_idiomas_libro_id FOREIGN KEY (libro_id) REFERENCES public.libros(id);


--
-- PostgreSQL database dump complete
--

